### ISSUE TITLE
Working Solution?

### ISSUE THREAD

**Issue by impartdan** [TheExtensionLab/Magento2Sass#2]
Did you ever get this figured out?

**Comment by JamesAnelay** [comment]
So not really this will process a basic sass file to css, the bit I got stuck at however is the @import in the sass, I need to set a path for the base @import and I have no idea what it should be or even whats going on.

Too confusing for me 🙈

**Comment by impartdan** [comment]
Bummer. I'll see if I have any better luck.

**Comment by JamesAnelay** [comment]
Let me know how you get(got) on.
